security:
    providers:
          in_memory:
              memory:
                  users:
                      Alejandro:
                          password: alejandro
                          roles: 'ROLE_USER'
                      Admin:
                          password: admin
                          roles: 'ROLE_ADMIN'
    encoders:
              Symfony\Component\Security\Core\User\UserInterface: plaintext
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
                    anonymous: ~
                    form_login:
                        login_path: /deportes/login
                        check_path: /deportes/login
                        default_target_path: /deportes
                        always_use_default_target_path: true
                    logout:
                        path:   /deportes/logout
                        target: /deportes


            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
